export const CollectionEndStatuses = [
  'COMPLETED',
  'COMPLETED PARTIAL',
  'COMPLETED EMPTY',
  'FAILED',
  'WAITING FOR AUTHENTICATION',
  'AUTHENTICATION CANCELLED',
  'AUTHENTICATION CONFLICT',
  'INCORRECT CREDENTIALS',
  'CUSTOMER ENROLLMENT REQUIRED',
  'CONTACT FORM',
  'KYC FORM',
];
